### ISSUE TITLE
.Net 6 Ubuntu jammy 22.04 base image upgrade. GSSAPI NTLM error

### ISSUE THREAD

**Issue by SaravanakumBalach** [gssapi/gss-ntlmssp#102]
Hi,

We are planning to upgrade our .Net core MVC application from .Net 6 to .Net 8 version. It is written in C#. To prepare for that upgrade we first upgraded from ubuntu 20.04 to ubuntu 22.04. We target ubuntu 22.04 version jammy tag with amd64 architecture.

This is our base image in the Docker file and the following line updates our package list.

FROM artifactory.xyz.com/dockerhub-microsoft/dotnet/aspnet:6.0-jammy-amd64 AS base

&& apt-get update && apt-get install -y --no-install-recommends curl gss-ntlmssp tzdata \

When our application tries to authenticate and open SSRS reports we get "GSSAPI operation failed with error - Unspecified GSS failure. Minor code may provide more information (Crypto routine failure)"

We were previously using focal base image in 20.04 version and was able to render SSRS reports. Did something change with gss-ntlmssp package in 22.04 version? I was reading some other posts where it says this issue is related to incompatibilities between OpenSSL 3.0 and the older cryptographic algorithms involved in NTLM authentication.  Any thoughts on how to fix this issue? Appreciate your kind response.

**Comment by simo5** [comment]
Sorry I do not know what version is packaged in Ubuntu versions, please provide information on what version of gss-ntlmssp is in use and what version of openssl it is compiled against.

You may want to also look at the recently closed #97 and open a bug in Ubuntu to update gss-ntlmssp accordingly if that is an issue.

**Comment by SaravanakumBalach** [comment]
Thanks for your response @simo5. We are using ubuntu 22.04 which has gss-ntlmssp 0.7.0 version and openssl 3.0.2 version.

**Comment by simo5** [comment]
In this case it is not a bug, Ubuntu 22 simply has an obsolete version of gss-ntlmssp.
I suggest you rebuild gss-ntlmssp anew, there are countless of improvements, some developed together with the .NET maintainers in later versions.
