### ISSUE TITLE
LMOWFv1 with passwords > 14 chars

### ISSUE THREAD

**Issue by jborean93** [gssapi/gss-ntlmssp#23]
The MS-NLMP docs define the [LMOWFv1 function as](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/464551a8-9fc4-428e-b3d3-bc5bfb2e73a5)

```
 Define LMOWFv1(Passwd, User, UserDom) as
        ConcatenationOf( DES( UpperCase( Passwd)[0..6],"KGS!@#$%"),
                  DES( UpperCase( Passwd)[7..13],"KGS!@#$%")) 
```

It also states that

> Password of the user. If the password is longer than 14 characters, the LMOWF v1 cannot be computed.  For LMOWF v1, if the password is shorter than 14 characters, it is padded by appending zeroes. 

While this is correct for LM hash authentication, this hash is still computed even if NTv1 hashes are used stopping longer passwords being used for NTv1. The check [here](https://github.com/gssapi/gss-ntlmssp/blob/0279a3e8209de555476b2ce075f949fb82913bb2/src/ntlm_crypto.c#L99) will block the initiator from acquiring a credential even if they want to use just NTv1 and not LMv1 authentication.

**Comment by simo5** [comment]
The question is what to do in KXKEY is extended security is not negotiated, I am preparing a tentative patch for this case.

**Comment by simo5** [comment]
I have two options here:
https://github.com/simo5/gssntlmssp/tree/nolmkey1
and
https://github.com/simo5/gssntlmssp/tree/nolmkey2

I have a feeling #2 is the way to go as that what windows machines have at hand after local authentication (or in the DCs).

@jborean93 what do you think?

**Comment by jborean93** [comment]
I think 2 makes more sense as well, if a user's password is greater than 14 characters then LM auth will never work even if the server is set to store the LM hash. It's also a less invasive change than option 1, I would only suggest having a comment saying why the LM hash is 0'd out.

**Comment by simo5** [comment]
done PTAL
