### ISSUE TITLE
Migration to Weblate

### ISSUE THREAD

**Issue by Jibec** [gssapi/gss-ntlmssp#39]
this is a follow-up of: https://pagure.io/gssntlmssp/issue/15

I migrated your project, you have a first PR here: https://github.com/gssapi/gss-ntlmssp/pull/38
you can keep it open as long as you wish, Weblate will reuse it and squash commits per author to limit the number of commits

Weblate will update all po files each time you change the pot file.
Weblate will update your LINGUAS file to keep your like easier.

please connect to https://translate.fedoraproject.org/ so I can make you admin

kind advice:

* please rewrite your readme in Pagure so we don't loose time (yes, you wrote you migrated to github, but I missed it, other will loose time too)
* if you choose not to forward issues to github, please close all Pagure issues, at least we would be informed of the transfer
* as a translator, have no idea what your project does, having example on where it is used would help me

**Comment by frozencemetery** [comment]
> please rewrite your readme in Pagure so we don't loose time (yes, you wrote you migrated to github, but I missed it, other will loose time too)

Can you give suggestions here?  It says "This project has been moved to github" in big letters at the very top, so it's not clear to me what you're for.

**Comment by simo5** [comment]
@Jibec I changed the README and removed all content but the notice that the project moved, hope that works better.
I also temporarily re-enabled the issue tracker and closed all the remaining issues with a message that the project moved.

HTH

**Comment by simo5** [comment]
I also logged on weblate, is that sufficient to "connect" ?

**Comment by simo5** [comment]
@Jibec also note that we changed the license, is that something that I can change in weblate once you make me admin ?

**Comment by simo5** [comment]
@Jibec, one more question, weblate keeps rebasing the PR while is open, is there any signal that will tell me when the translator thinks it is "done" ?

**Comment by Jibec** [comment]
> I also logged on weblate, is that sufficient to "connect" ?

yes, you are now admin

> @Jibec also note that we changed the license, is that something that I can change in weblate once you make me admin ?

as long as it still it opensource, yes, no problem

> @Jibec, one more question, weblate keeps rebasing the PR while is open, is there any signal that will tell me when the translator thinks it is "done" ?

No, why?

When you notice a translation is complete, you are welcome to release.
When you want to release for whatever reason, you merge what is ready.
The best is either to inform translators about an incoming release or make frequent release. But that's easy to say.

**Comment by simo5** [comment]
@Jibec sorry but I do not see a way to change the translation license ...

**Comment by simo5** [comment]
Found it, nvm
