### ISSUE TITLE
Possible unintended code typo (`&` instead of `|`)

### ISSUE THREAD

**Issue by filipnavara** [gssapi/gss-ntlmssp#56]
https://github.com/gssapi/gss-ntlmssp/blob/9b6493b1419d615e347d67c636fd238aa4d0f780/src/gss_sec_ctx.c#L401

**Comment by simo5** [comment]
Duh!
That is embarrassing :-D

**Comment by simo5** [comment]
The sad thing is that tests pass either way, so it means that part is not tested ... somehow

**Comment by simo5** [comment]
Ah this break just the reporting, that is why, as the NTLMSSP flags are what are used to do the negotiation ...
Fix incoming.

**Comment by filipnavara** [comment]
Thanks! It didn't actually break any scenario I was testing. I found it when looking at the `GSS_C_INTEG_FLAG` code and looking for implications of setting the flag when doing client-side negotiation.

**Comment by simo5** [comment]
As soon as tests pass I'll merge, thanks for spotting this, really appreciated.
