### ISSUE TITLE
NTLM fails on Ubuntu 22.04 with OpenSSL 3.0

### ISSUE THREAD

**Issue by wfurt** [gssapi/gss-ntlmssp#71]
It seems like OpenSSL 3.0 (at least on Ubuntu) retired md4.
```
# openssl md4
Error setting digest
4037123E367F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (MD4 : 88), Properties ()
4037123E367F0000:error:03000086:digital envelope routines:evp_md_init_internal:initialization error:../crypto/evp/digest.c:237:
```

authentication fails with unknown GSS error: https://github.com/dotnet/runtime/issues/67353
Perhaps gss-ntlm should have fall-back implementation instead of depending on OpenSSL.

**Comment by wfurt** [comment]
dup of https://github.com/gssapi/gss-ntlmssp/issues/71.

**Comment by simo5** [comment]
Ah yeah, in openssl 3.0 the legacy provider is not enabled by default, thus MD4 may not work.
I have a way to re-enable MD4 only for specific operations, but that will also eventually fail once some distrinution decides to completeluy get rid of legacy algorithms, but will carry us there until then.
@wfurt Is this urgent for you to resolve ?

**Comment by simo5** [comment]
Note that in the short term a workaround is to change the openssl 3.0 configuration (system-wide) to enable the "legacy" provider.

**Comment by wfurt** [comment]
it seems like we are minutes apart with @filipnavara - closing and opening at the same tome from different continents :)

**Comment by wfurt** [comment]
I will check if installing legacy openssl and forcing to use it would fix the problem @simo5. if that works I think that can be workaround for some time for anybody who urgently needs to jump on new OS version.

**Comment by simo5** [comment]
Working on this here: #72
Is there a way to run check on 22.04 on github? my actions conf has ubuntu:latest but all i get is 20.04

**Comment by simo5** [comment]
@omajid annoying, but I guess will test the 3.0 code once github updates the images.
MEanwhile I tested locally on rawhide and #72 seem to work w/o issues

@wfurt can you test if PR #72 solves the problem for you w/o configureing openssl for legacy provider?

**Comment by omajid** [comment]
@simo5 I can't get Fedora containers to work, but you can see Ubuntu tests failing using this action: https://github.com/omajid/gss-ntlmssp/blob/ci-actions-containers/.github/workflows/ccpp.yml. Result: https://github.com/omajid/gss-ntlmssp/actions/runs/2073611521

**Comment by omajid** [comment]
If you can help me work around ` configure: error: GSSAPI library does not support gss_import_cred` on Fedora, I can clean it up and do a PR.

**Comment by simo5** [comment]
What version of Fedora?
As long as you have krb5-devel installed all should work fine

**Comment by omajid** [comment]
Fedora 35. See the `configure` section at https://github.com/omajid/gss-ntlmssp/runs/5778418850?check_suite_focus=true:

```
checking for krb5-config... /usr/bin/krb5-config
checking for gss_import_cred in -lgssapi_krb5... no
configure: error: GSSAPI library does not support gss_import_cred
```

krb5-devel is installed earlier:

```
 krb5-devel                             x86_64  1.19.2-2.fc35              fedora   140 k
```

**Comment by simo5** [comment]
you need these packages installed to build:
BuildRequires: autoconf
BuildRequires: automake
BuildRequires: libtool
BuildRequires: m4
BuildRequires: libxslt
BuildRequires: libxml2
BuildRequires: docbook-style-xsl
BuildRequires: doxygen
BuildRequires: gettext-devel
BuildRequires: pkgconfig
BuildRequires: krb5-devel >= 1.11.2
BuildRequires: libunistring-devel
BuildRequires: openssl-devel
BuildRequires: pkgconfig(wbclient)
BuildRequires: zlib-devel
BuildRequires: make

wbclient is actually optional, but it is easy to install via libwbclient-devel

**Comment by omajid** [comment]
Yup, I grabbed all the dependencies from the Fedora 35 spec file too. Still doesn't seem to work.

```
dnf install -y autoconf automake docbook-style-xsl doxygen gettext-devel krb5-devel libtool libunistring-devel libxml2 libxslt m4 make openssl-devel pkgconfig 'pkgconfig(wbclient)' zlib-devel
```

**Comment by simo5** [comment]
Something fishy here gss_import_cred is supported since ages

**Comment by simo5** [comment]
I tested this morning on rawhide (F37) installed from scratch (container image) and worked just fine.
It should work just fin in f35 too though

**Comment by simo5** [comment]
Uhm I had missed installing libtool, all seem to be working fine now even after autoreconf

**Comment by simo5** [comment]
This should be fixed in main now, please reopen or a file a new one in case of more issues
