### ISSUE TITLE
gss_wrap/gss_unwrap should work on connection without NEGOTIATE_SEAL

### ISSUE THREAD

**Issue by filipnavara** [gssapi/gss-ntlmssp#77]
Let's start with a bit of a background.

RFC 2222 originally specified the GSSAPI SASL mechanism for authentication. It didn't specifically tie the mechanism to Kerberos unlike the later RFC 4752 revision. As a last step of the authentication exchange the server sends a token with supported protection schemes and maximum token size to the client. This is encoded with `GSS_Wrap` API with `conf_flag == 0`. The client decodes it with `GSS_Unwrap`, chooses the preferred protection for rest of communication, and then encodes the reply with `GSS_Wrap` and sends it back to server.

Microsoft Exchange implements this mechanism for authentication to SMTP, IMAP and POP3 services. It works with Negotiate, Kerberos and NTLM protocols. The NTLM one is particularly tricky because the semantics for `GSS_Warp`/`GSS_Unwrap` are not fully covered by the specifications. So I went ahead, set up an Exchange server with Windows AD and tested what is really sent on the wire.

---

In case NEGOTIATE_SEAL is negotiated in the initial authentication the gss-ntlmssp library is already interoperable. The `conf_flag` is ignored (not a surprise since NTLM doesn't have a way to transmit the flag on the wire like Kerberos does), sealing and signing is applied.

In case NEGOTIATE_SEAL is NOT negotiated and NEGOTIATE_SIGN+NEGOTIATE_KEY_EXHANGE were negotiated the tokens should still be sealed with the computed key and signed. gss-ntlmssp currently doesn't [implement that](https://github.com/gssapi/gss-ntlmssp/blob/a898099deccac30a56c3af97f255045f86f5c36f/src/ntlm_crypto.c#L905-L908).

I didn't check the behavior for other flag combinations yet. I am not particularly interested in them because anything without MIC calculation downgrades the security beyond a point where latest Windows versions may reject it.

---

Notably, I would expect the `GSS_Wrap` behavior to align with the behavior of the `EncryptMessage` (NTLM) API on Windows with the data buffer not having the `SECBUFFER_READONLY` flag and the `conf_flag` flag matching the `SECQOP_WRAP_NO_ENCRYPT` flag. That means always sealing the data (at least for NTLM2 w/ key exchange) and ignoring the `conf_flag` flag.

Confusingly, the [NegotiateStream specification](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-NNS/[MS-NNS].pdf) is also defined in terms of `GSS_Wrap`/`GSS_Unwrap` methods. Unlike the SMTP authentication it behaves differently on NTLM where it sends the messages as `<signature token><unsealed message>` if `NEGOTIATE_SEAL` was not specified. This difference is caused by a special NTLM code path in the `NegotiateStream` code that passes the `SECBUFFER_READONLY` flag to the `EncryptMessage`/`DecryptMessage` methods. The equivalent GSSAPI transformation is to call `gss_get_mic` to produce the `<signature token>` and use `gss_verify_mic` to verify it. This cannot be expressed with `GSS_Wrap`/`GSS_Unwrap` directly.

**Comment by simo5** [comment]
@filipnavara I finally came around to take a second good look at this.

So it seem the main issue here is my return of ENOSUP when NTLMSSP_NEGOTIATE_SEAL is not negotiated.

In this case I should check if NEGOTIATE_SIGN and NEGOTIATE_KEY_EXCHANGE are instead set and continue as normal calling ntlmv2-sign ... but in order to do that I would need a seal_handle, so I need to always create a seal handle regardless of negotiated flags.

Is this what you are suggesting?

**Comment by simo5** [comment]
And of curse if NEGOTIATE_SIGN is set we are already guaranteed to have a seal_handle ... so this is just about removing the flag check from ntlm_seal and ntlm_unseal ...

**Comment by filipnavara** [comment]
> Is this what you are suggesting?

Yep

> And of curse if NEGOTIATE_SIGN is set we are already guaranteed to have a seal_handle ... so this is just about removing the flag check from ntlm_seal and ntlm_unseal ...

I think so.

**Comment by simo5** [comment]
@filipnavara should this be conditional to anything?
I have a specific test to check thet gss_wrap does fail if NTLMSSP_SEAL is not negotiated, which obviously now fails.
I guess I should always ignore that/
Or should I check the gss and ntlm flags disjointly and fail if GSS_GONF_FLAG us not set ignoring the NTLM level negotiate flags?

**Comment by simo5** [comment]
Oh wait, I should juts apply the signature, but not seal the content, perhaps ?

**Comment by simo5** [comment]
NVM my last comment. It sounds like what we are doing here is that if the app ask to gss_wrap something we wrap it regardless of what we negotiated with the peer.
So basically we take these flags just as advisory and if the peer can't handle the message ... well too bad.

**Comment by filipnavara** [comment]
> should this be conditional to anything?

Good question. Unfortunately I don't have a good answer to that at the moment. If you have `seal_handle` then it should work and do sealing with the computed key.

> Oh wait, I should juts apply the signature, but not seal the content, perhaps ?

If you have `seal_handle` then it should do sealing regardles of `NTLMSSP_NEGOTIATE_SEAL`. The experiments I did on Windows showed that it didn't just copy plain text data.

I am not sure what should be the behavior if you don't have `seal_handle`. The option is either to fail with `ENOTSUP` (like implemented today) or to copy the plain text verbatim. I can do some experiments on Windows to see what `EncryptMessage` API does in that case but I am generally fine with keeping the current behavior in that case (`ENOTSUP`).

**Comment by simo5** [comment]
seal_handle is always generated regardless, so I am just going to return EINVAL if it is missing.
As for behavior, I'll let applications just gss_wrap all they want.
If they really just want a signature GSSAPI requires they use gss_get_mic() already, so the application retains all the options.

Flags can also be checked by applications so they have all the tools needed to decide whether to use gss_warp() or just gss_get_mic() if the protocol requires a choice be made.

**Comment by simo5** [comment]
Btw I wonder if any of the dotnet test suite can be easily run in a container w/o rebuilding all of it, I think it might be a good idea to run at least some dotnet tests when I change gssntlmssp to insure things don't break.
Alternatively if you can schedule a weekly(?) run in dotnet CI when gssntlmssp changes, and pested me if ntlm related tests fails that could also be an option :-)

**Comment by filipnavara** [comment]
The dotnet test suites actually have very small coverage right now so it's likely not worth the effort, at least not yet. Some of the tests require complex Docker setup. I started working on expanding them and making it all easier to run but it's pretty slow effort so far. That said, I am aware that there is interest in the area of sharing the testing infrastructure and I regularly discuss that both with the .NET Networking team and other people working on various libraries in the ecosystem...
