### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [gssapi/gss-ntlmssp#79]
Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

Thanks in advance.

**Comment by simo5** [comment]
NTLMSSP like any other GSSAPI mechanism is completely oblivious to what data is passed in the gss_channel_bindings_t structure. The spec just indicates what applications should use.

Is there any change to the structure of gss_channel_bindings_t I missed?

**Comment by filipnavara** [comment]
After reading the specification and looking into the implementations yesterday I agree with @simo5's conclusion that there's no change necessary in any GSSAPI mechanism. The GSSAPI mechanisms simply runs a hash function on the opaque data supplied by the application.

A good self-contained example of how the whole flow works is [PSOpenAD](https://github.com/jborean93/PSOpenAD) project which calls GSSAPI and has the [code to calculate the channel binding](https://github.com/jborean93/PSOpenAD/blob/0c6c891287f14c589af83dcc116defd3b7c8eb3d/src/Session.cs#L357-L402) which is then wrapped into `gss_channel_bindings_t` and passed to GSSAPI.

**Comment by simo5** [comment]
Ok, not a bug or feature then.
