### ISSUE TITLE
sigsegv on gss_sec_ctx.c:643

### ISSUE THREAD

**Issue by SergeyPachkov** [gssapi/gss-ntlmssp#83]
Hello 

I received SIGSEGV on https://github.com/gssapi/gss-ntlmssp/blame/main/src/gss_sec_ctx.c#L643
cred == nullptr in case  of acceptor_cred_handle is null 

example call in dcerpc: https://github.com/dcerpc/dcerpc/blob/master/dcerpc/ncklib/gssauthcn.c#L2463
or in more "fresh" apple's code: https://github.com/apple-oss-distributions/dcerpc/blob/main/dcerpc/ncklib/gssauthcn.c#L2458

Could you fix crash?

**Comment by simo5** [comment]
Please check if #84 fixes it for you

**Comment by SergeyPachkov** [comment]
Yes, it works for me
